### ISSUE TITLE
Why make a new repo?

### ISSUE THREAD

**Issue by Davenporten** [pradel/create-react-app-swc#14]
I haven't really looked through this repo, but I just was wondering why you decided to make a new repo for this rather than trying to make a PR for https://github.com/facebook/create-react-app to create an option to create a React app using swc. If you were able to get it in there would probably be more adoption. But I also realize I might not see the whole picture so I'm curious if you've thought of this and maybe had particular reasons not to pursue it.

**Comment by Davenporten** [comment]
Seems like there is already talk about this: https://github.com/facebook/create-react-app/issues/8060. Again, I am probably not considering something.

**Comment by pradel** [comment]
Hey, I could have opened a pr there, but people would not be able to actually use it until it's merged and released. As the maintenance of CRA is pretty slow I didn't want to go down that road. The repo was created more than a year ago, at this time swc was very experimental and the chance for CRA to add it was almost inexistent.

**Comment by pradel** [comment]
Looking forward to CRA having native SWC support!

**Comment by Davenporten** [comment]
> Hey, I could have opened a pr there, but people would not be able to actually use it until it's merged and released. As the maintenance of CRA is pretty slow I didn't want to go down that road. The repo was created more than a year ago, at this time swc was very experimental and the chance for CRA to add it was almost inexistent.

Cool, gotcha. Well it's awesome you're doing this here, I'm definitely a big swc fan myself.
