### ISSUE TITLE
Hot refresh

### ISSUE THREAD

**Issue by jacob-j** [pradel/create-react-app-swc#5]
Hello guys!
Fantastic setup, we have begun testing this with our large react app.
Everything seems to be running fine, except Hot Refresh when recompiling due to file change.

Have we done something wrong in our config?
We tried adding .swcrc with `jsc.transform.react `set to `"automatic"`.
We also tried adding the same to the `swc-loader` plugin.

**Comment by jacob-j** [comment]
Temporary solution is disabling hot refresh, as demonstrated here: https://stackoverflow.com/a/65543913
This works for now, not sure why hot refresh is not working, but seems to be a general problem with CRA

**Comment by pradel** [comment]
Yeah seems like a common problem, unfortunately.

**Comment by pradel** [comment]
I am closing this one as it's related to CRA
